name: Node CI

on:
  push:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: git commit and push dist
      uses: github-actions-x/commit@v2.2
      with:
        github-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        commit-message: '[AutoCommit] - Github Actions: Node CI build, commit, push dist'
